# Generated by Django 5.0.6 on 2024-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
